## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = './data/'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [7]:
app_train.shape

(307511, 122)

#### 列出所有欄位

In [15]:
app_train.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

#### 截取部分資料

In [19]:
app_train.loc[100:2000]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
100,100119,0,Revolving loans,F,N,Y,0,54000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
101,100120,0,Cash loans,F,N,N,0,135000.0,781920.0,28215.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
102,100121,0,Cash loans,M,N,Y,0,126000.0,787131.0,26145.0,...,0,0,0,0,1.0,1.0,0.0,0.0,0.0,1.0
103,100122,0,Cash loans,F,N,N,1,76500.0,808650.0,26217.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
104,100123,0,Cash loans,F,N,N,0,103500.0,675000.0,19737.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
105,100124,0,Cash loans,M,N,Y,0,225000.0,448272.0,28647.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
106,100125,0,Cash loans,F,N,N,0,126000.0,263686.5,26208.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
107,100126,0,Revolving loans,M,N,Y,2,135000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
108,100127,0,Cash loans,M,N,Y,0,112500.0,52128.0,5341.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
109,100129,0,Revolving loans,F,Y,Y,1,85500.0,135000.0,6750.0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0
110,100130,1,Cash loans,F,N,Y,1,157500.0,723996.0,30802.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
111,100131,0,Cash loans,F,N,Y,0,270000.0,891072.0,45625.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
112,100132,0,Cash loans,F,N,Y,0,202500.0,1136439.0,73611.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
113,100133,0,Cash loans,F,N,N,0,67500.0,384048.0,18810.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
114,100134,0,Revolving loans,F,N,N,0,202500.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
115,100135,0,Cash loans,M,N,Y,0,135000.0,391194.0,26271.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
116,100136,0,Cash loans,M,Y,N,1,157500.0,1571931.0,49356.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
117,100137,0,Cash loans,F,Y,Y,0,225000.0,891072.0,45625.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
118,100138,0,Cash loans,M,Y,N,0,135000.0,824823.0,29223.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
119,100139,0,Cash loans,F,N,N,1,157500.0,302341.5,24016.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
120,100140,0,Revolving loans,F,N,N,0,157500.0,675000.0,33750.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
121,100142,0,Cash loans,M,Y,Y,1,360000.0,579195.0,27994.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
122,100143,0,Revolving loans,M,N,Y,0,162000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
123,100144,0,Cash loans,F,N,N,0,112500.0,535500.0,30028.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
124,100145,0,Cash loans,F,Y,Y,1,202500.0,260725.5,16789.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
125,100146,0,Cash loans,M,Y,Y,0,117000.0,327024.0,12456.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
126,100147,0,Cash loans,F,N,Y,1,135000.0,518562.0,22099.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
127,100148,0,Cash loans,F,N,Y,0,247500.0,755190.0,36459.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
128,100149,0,Cash loans,M,Y,N,0,171000.0,539590.5,26374.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
129,100151,0,Cash loans,M,N,N,0,135000.0,182016.0,11772.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1971,102312,0,Cash loans,F,N,Y,0,81000.0,283500.0,13765.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
1972,102313,0,Revolving loans,F,N,Y,2,171000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1973,102314,0,Cash loans,F,Y,N,1,225000.0,675000.0,28728.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1974,102316,0,Cash loans,F,Y,Y,2,270000.0,713889.0,43803.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
1975,102317,0,Cash loans,M,Y,Y,0,360000.0,1006920.0,51412.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1976,102318,0,Cash loans,M,Y,Y,0,112500.0,158301.0,15552.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1977,102319,0,Cash loans,M,Y,Y,0,135000.0,314055.0,17167.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1978,102320,0,Cash loans,F,N,Y,0,165150.0,595759.5,39811.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,7.0
1979,102321,0,Cash loans,F,N,Y,1,99000.0,622413.0,33894.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
1980,102322,0,Cash loans,F,N,Y,0,202500.0,942300.0,30528.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1981,102323,0,Cash loans,F,N,Y,0,270000.0,792162.0,38241.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
1982,102324,0,Cash loans,F,Y,Y,0,261000.0,1227901.5,46899.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
1983,102325,0,Revolving loans,F,N,Y,0,157500.0,180000.0,9000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1984,102326,0,Cash loans,F,N,Y,1,45000.0,135000.0,7321.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1985,102327,0,Cash loans,M,N,N,1,180000.0,649462.5,24196.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
1986,102328,0,Cash loans,F,N,Y,0,94500.0,204768.0,7483.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1987,102329,0,Cash loans,M,N,Y,0,225000.0,447768.0,35374.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,8.0
1988,102330,0,Cash loans,F,N,N,0,67500.0,508495.5,21672.0,...,0,0,0,0,0.0,0.0,0.0,1.0,2.0,1.0
1989,102331,0,Revolving loans,F,N,N,1,54000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1990,102332,0,Cash loans,F,N,Y,0,112500.0,284400.0,15880.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
1991,102333,0,Cash loans,F,N,Y,0,135000.0,1061599.5,31171.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1992,102334,1,Cash loans,M,Y,Y,1,229500.0,888840.0,29376.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1993,102335,0,Cash loans,M,N,Y,1,189000.0,1133662.5,45090.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
1994,102336,0,Cash loans,M,Y,Y,0,315000.0,273636.0,29601.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
1995,102337,1,Cash loans,F,N,Y,0,49500.0,130824.0,5062.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,5.0
1996,102338,0,Cash loans,M,Y,Y,0,135000.0,254700.0,17019.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1997,102339,0,Revolving loans,F,Y,N,1,135000.0,202500.0,10125.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
1998,102341,0,Revolving loans,F,N,N,2,202500.0,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,3.0
1999,102343,0,Cash loans,M,N,Y,1,180000.0,810000.0,21496.5,...,0,0,1,0,0.0,0.0,0.0,0.0,0.0,1.0
2000,102345,0,Cash loans,F,N,Y,0,225000.0,820638.0,32674.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子